// styles.js — all inline style objects for StellarVote
// Kept separate from App.js for readability and maintainability.
// Import with: import S from "./styles";

// ─── Design Tokens ────────────────────────────────────────────────────────────
export const colors = {
  bg:          "#070b14",
  bgCard:      "#0c1526",
  bgDeep:      "#0a1628",
  bgInput:     "#0f1f38",
  bgTx:        "#0c1a30",
  border:      "#1a2236",
  borderCard:  "#1e2d48",
  borderBlue:  "#1e3a5f",
  borderTx:    "#142340",
  borderInput: "#1a3050",
  textPrimary: "#e8edf7",
  textMuted:   "#6b7fa3",
  textMono:    "#94a3c4",
  textFeed:    "#c4d0e8",
  purple:      "#7c3aed",
  purpleLight: "#8b5cf6",
  purplePale:  "#a78bfa",
  blue:        "#38bdf8",
  indigo:      "#818cf8",
  green:       "#10b981",
  greenDark:   "#059669",
  red:         "#dc2626",
  redLight:    "#fca5a5",
  amber:       "#f59e0b",
};

// ─── Style Map ────────────────────────────────────────────────────────────────
const S = {

  // Layout
  root: {
    minHeight: "100vh",
    background: colors.bg,
    fontFamily: "'Inter', system-ui, sans-serif",
    color: colors.textPrimary,
    display: "flex",
    flexDirection: "column",
  },
  body: {
    display: "flex",
    flex: 1,
  },

  // Navigation bar
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "18px 32px",
    borderBottom: `1px solid ${colors.border}`,
    background: "rgba(7,11,20,0.95)",
    backdropFilter: "blur(12px)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logo: {
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: "-0.5px",
    background: `linear-gradient(90deg, ${colors.purple}, ${colors.blue})`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  contractPill: {
    fontSize: 11,
    padding: "5px 12px",
    borderRadius: 20,
    background: colors.bgInput,
    border: `1px solid ${colors.borderBlue}`,
    color: colors.blue,
    textDecoration: "none",
  },

  // Sidebar
  sidebar: {
    width: 290,
    flexShrink: 0,
    padding: "24px 16px",
    borderRight: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    overflowY: "auto",
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 2,
  },

  // Wallet cards
  walletCard: {
    borderRadius: 14,
    border: `1px solid ${colors.borderCard}`,
    padding: "14px 16px",
    cursor: "pointer",
    transition: "all 0.2s",
    background: colors.bgCard,
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  walletIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    background: "#111827",
    flexShrink: 0,
  },
  walletInfo: {
    flex: 1,
    minWidth: 0,
  },
  walletName: {
    fontSize: 15,
    fontWeight: 700,
    marginBottom: 3,
  },
  walletTag: {
    fontSize: 11,
    color: colors.textMuted,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  walletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    flexShrink: 0,
  },

  // Connected wallet panel
  connectedCard: {
    borderRadius: 14,
    border: `1px solid ${colors.borderBlue}`,
    padding: "16px",
    background: colors.bgDeep,
  },
  balanceLbl: {
    fontSize: 11,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  balanceNum: {
    fontSize: 30,
    fontWeight: 800,
    background: `linear-gradient(90deg, ${colors.blue}, ${colors.indigo})`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    marginBottom: 2,
  },
  addrRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    padding: "7px 10px",
    borderRadius: 8,
    background: colors.bgInput,
    border: `1px solid ${colors.borderInput}`,
  },
  addrText: {
    flex: 1,
    fontSize: 12,
    color: colors.textMono,
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: colors.textMuted,
    fontSize: 14,
    padding: "2px",
    lineHeight: 1,
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
  },
  actionRow: {
    display: "flex",
    gap: 8,
    marginTop: 10,
  },
  actionBtn: {
    flex: 1,
    padding: "10px 0",
    borderRadius: 9,
    border: "none",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
    textAlign: "center",
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // Recent transactions
  txList: {
    marginTop: 10,
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  txItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 8,
    background: colors.bgTx,
    border: `1px solid ${colors.borderTx}`,
  },
  txDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    flexShrink: 0,
  },
  txHash: {
    flex: 1,
    fontSize: 11,
    color: colors.textMono,
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textDecoration: "none",
  },
  txTime: {
    fontSize: 11,
    color: colors.textMuted,
    flexShrink: 0,
  },
  disconnectBtn: {
    width: "100%",
    padding: "9px",
    borderRadius: 9,
    background: "transparent",
    border: `1px solid #2a1a3a`,
    color: colors.purpleLight,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 4,
  },

  // Main content area
  main: {
    flex: 1,
    padding: "24px 28px",
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },

  // Poll card
  pollCard: {
    borderRadius: 18,
    border: `1px solid ${colors.borderCard}`,
    padding: "28px",
    background: "linear-gradient(135deg, #0c1526 60%, #0d1a33)",
    flex: 1,
  },
  pollTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: colors.purple,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  pollQuestion: {
    fontSize: 22,
    fontWeight: 800,
    lineHeight: 1.3,
    marginBottom: 24,
    color: colors.textPrimary,
  },
  voteRow: {
    display: "flex",
    gap: 16,
    marginBottom: 26,
  },
  voteBtn: {
    flex: 1,
    padding: "18px 0",
    borderRadius: 14,
    border: "none",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.2s",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  },
  voteCount: {
    fontSize: 32,
    fontWeight: 900,
  },
  voteLabel: {
    fontSize: 12,
    opacity: 0.85,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  barWrap: {
    background: colors.bgInput,
    borderRadius: 10,
    height: 10,
    overflow: "hidden",
    marginBottom: 10,
  },
  barFill: {
    height: "100%",
    background: `linear-gradient(90deg, ${colors.greenDark}, ${colors.blue})`,
    borderRadius: 10,
    transition: "width 0.6s ease",
  },
  barLabels: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 18,
  },
  statusBar: {
    padding: "11px 14px",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  txHashLink: {
    fontSize: 11,
    color: colors.blue,
    fontFamily: "monospace",
    textDecoration: "none",
  },

  // Activity feed
  feedCard: {
    borderRadius: 18,
    border: `1px solid ${colors.borderCard}`,
    padding: "20px 24px",
    background: colors.bgCard,
  },
  feedHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  feedTitle: {
    fontSize: 16,
    fontWeight: 700,
  },
  livePill: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: colors.green,
    background: "rgba(16,185,129,0.1)",
    border: "1px solid rgba(16,185,129,0.3)",
    borderRadius: 20,
    padding: "3px 10px",
  },
  feedItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 10,
    marginBottom: 4,
  },
  feedAddr: {
    flex: 1,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "monospace",
    color: colors.textFeed,
  },
  feedVoteBadge: {
    fontSize: 11,
    fontWeight: 700,
    padding: "3px 10px",
    borderRadius: 20,
    letterSpacing: 0.5,
  },
  feedTime: {
    fontSize: 11,
    color: colors.textMuted,
    flexShrink: 0,
  },

  // Error box
  errorBox: {
    padding: "10px 14px",
    borderRadius: 10,
    background: "rgba(220,38,38,0.1)",
    border: "1px solid rgba(220,38,38,0.3)",
    color: colors.redLight,
    fontSize: 12,
  },

  // Send XLM modal
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.75)",
    zIndex: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    background: colors.bgCard,
    border: `1px solid ${colors.borderBlue}`,
    borderRadius: 18,
    padding: "28px",
    width: 380,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 800,
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 10,
    background: colors.bgInput,
    border: `1px solid ${colors.borderInput}`,
    color: colors.textPrimary,
    fontSize: 13,
    fontFamily: "monospace",
    outline: "none",
    boxSizing: "border-box",
  },
  inputLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 6,
    display: "block",
  },
  amountWrap: {
    position: "relative",
  },
  maxBtn: {
    position: "absolute",
    right: 10,
    top: "50%",
    transform: "translateY(-50%)",
    background: colors.borderBlue,
    border: "none",
    color: colors.blue,
    fontSize: 11,
    fontWeight: 700,
    padding: "3px 8px",
    borderRadius: 6,
    cursor: "pointer",
  },
  modalBtns: {
    display: "flex",
    gap: 10,
    marginTop: 4,
  },
  sendBtn: {
    flex: 1,
    padding: "13px",
    borderRadius: 10,
    border: "none",
    background: `linear-gradient(135deg, ${colors.purple}, ${colors.blue})`,
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
  },
  cancelBtn: {
    padding: "13px 20px",
    borderRadius: 10,
    background: colors.bgInput,
    border: `1px solid ${colors.borderInput}`,
    color: colors.textMono,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
};

export default S;